name: Build site

on:
  push:
    branches:
      - master

jobs:
  build-site:
    name: Build site
    runs-on: ubuntu-latest

    steps:
      - name: Build static files
        run: echo "CHANGEME"
